# Wikipedia

In [3]:
%load_ext autoreload
%autoreload 2
import os
import sys
import inspect

currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parentdir = os.path.dirname(currentdir)
sys.path.append(parentdir)
sys.path.append("../")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [18]:
from sources.wikipedia.extractors import uruguay as uy
from sources.wikipedia.transformers import uruguay as tuy
from sources.wikipedia.app import ETLWikipediaHandler as etl

In [5]:
import pandas as pd

In [6]:
df = uy.extract_municipalities(url=uy.MUNICIPALITIES_URL)
df

,department,municipality,population,surface,mayor,creation
0,Artigas,Baltasar Brum,2608,"754,0 km²",Juan Marticorena (PN),2010-03-01
1,Artigas,Bella Unión,18 406,"547,0 km²",William Cresseri (PN),2010-03-01
2,Artigas,Tomás Gomensoro,2902,"804,5 km²",Federico Arbiza (PN),2010-03-01
3,Canelones,18 de Mayo,21 371,"11,0 km²",Adriana Sánchez (FA),2013-03-02
4,Canelones,Aguas Corrientes,1728,"51,5 km²",Marcelo Delgado (FA),2010-03-01
...,...,...,...,...,...,...
120,Treinta_y_Tres,General Enrique Martínez,(sin datos),(sin datos),Nidia Vera,2017-12-02
121,Treinta_y_Tres,Rincón,(sin datos),(sin datos),Eduardo Gonzales,2017-12-02
122,Treinta_y_Tres,Santa Clara de Olimar,2485,"482,4 km²",Pablo Echevarría (PN),2010-03-01
123,Treinta_y_Tres,Vergara,4064,"622,5 km²",José González (PN),2010-03-01
124,Treinta_y_Tres,Villa Sara,(sin datos),(sin datos),Analía Larrañaga,2017-12-02

In [7]:
country = "Uruguay"

In [8]:
(
    summary,
    history,
    divisions, 
    municipalities
) = uy.fetch_data(country)

From census 2011

In [9]:
from IPython.display import display
from rapidfuzz.fuzz import token_sort_ratio as tsr

In [10]:
display(divisions)
display(municipalities)

        department                 capital  area_km2  area_mi2  population
0       Montevideo              Montevideo       530       200     1319108
1        Canelones               Canelones      4536      1751      520187
2        Maldonado               Maldonado      4793      1851      164300
3            Salto                   Salto     14163      5468      124878
4          Colonia  Colonia del Sacramento      6106      2358      123203
5         Paysandú                Paysandú     13922      5375      113124
6         San José        San José de Mayo      4992      1927      108309
7           Rivera                  Rivera      9370      3620      103493
8       Tacuarembó              Tacuarembó     15438      5961       90053
9      Cerro Largo                    Melo     13648      5270       84698
10         Soriano                Mercedes      9008      3478       82595
11         Artigas                 Artigas     11928      4605       73378
12           Rocha                   Rocha     10551      4074       68088
13         Florida                 Florida     10417      4022       67048
14       Lavalleja                   Minas     10016      3867       58815
15         Durazno                 Durazno     11643      4495       57088
16       Río Negro             Fray Bentos      9282      3584       54765
17  Treinta y Tres          Treinta y Tres      9529      3679       48134
18          Flores                Trinidad      5144      1986       25050

,department,municipality,population,surface,mayor,creation
0,Artigas,Baltasar Brum,2608,"754,0 km²",Juan Marticorena (PN),2010-03-01
1,Artigas,Bella Unión,18 406,"547,0 km²",William Cresseri (PN),2010-03-01
2,Artigas,Tomás Gomensoro,2902,"804,5 km²",Federico Arbiza (PN),2010-03-01
3,Canelones,18 de Mayo,21 371,"11,0 km²",Adriana Sánchez (FA),2013-03-02
4,Canelones,Aguas Corrientes,1728,"51,5 km²",Marcelo Delgado (FA),2010-03-01
...,...,...,...,...,...,...
120,Treinta_y_Tres,General Enrique Martínez,(sin datos),(sin datos),Nidia Vera,2017-12-02
121,Treinta_y_Tres,Rincón,(sin datos),(sin datos),Eduardo Gonzales,2017-12-02
122,Treinta_y_Tres,Santa Clara de Olimar,2485,"482,4 km²",Pablo Echevarría (PN),2010-03-01
123,Treinta_y_Tres,Vergara,4064,"622,5 km²",José González (PN),2010-03-01
124,Treinta_y_Tres,Villa Sara,(sin datos),(sin datos),Analía Larrañaga,2017-12-02

In [11]:
dfd = divisions.copy()
dfm = municipalities.copy()

In [12]:
dfd["_muni_dept"] = dfm["department"].copy().unique()
dfd

,department,capital,area_km2,area_mi2,population,_muni_dept
0,Montevideo,Montevideo,530,200,1319108,Artigas
1,Canelones,Canelones,4536,1751,520187,Canelones
2,Maldonado,Maldonado,4793,1851,164300,Cerro_Largo
3,Salto,Salto,14163,5468,124878,Colonia
4,Colonia,Colonia del Sacramento,6106,2358,123203,Durazno
5,Paysandú,Paysandú,13922,5375,113124,Flores
6,San José,San José de Mayo,4992,1927,108309,Florida
7,Rivera,Rivera,9370,3620,103493,Lavalleja
8,Tacuarembó,Tacuarembó,15438,5961,90053,Maldonado
9,Cerro Largo,Melo,13648,5270,84698,Montevideo
10,Soriano,Mercedes,9008,3478,82595,Paysandu
11,Artigas,Artigas,11928,4605,73378,Rio_Negro
12,Rocha,Rocha,10551,4074,68088,Rivera
13,Florida,Florida,10417,4022,67048,Rocha
14,Lavalleja,Minas,10016,3867,58815,Salto
15,Durazno,Durazno,11643,4495,57088,San_Jose
16,Río Negro,Fray Bentos,9282,3584,54765,Soriano
17,Treinta y Tres,Treinta y Tres,9529,3679,48134,Tacuarembo
18,Flores,Trinidad,5144,1986,25050,Treinta_y_Tres

In [13]:
def tokenize(row, pairs):
    for p in pairs:
        token = tsr(row["department"], p)
        if token > 85:
            return p
    return pd.NA

In [14]:
dfd["_dept"] = dfd.apply(lambda row: tokenize(row, dfd["_muni_dept"].to_list()), axis=1)
dfd

,department,capital,area_km2,area_mi2,population,_muni_dept,_dept
0,Montevideo,Montevideo,530,200,1319108,Artigas,Montevideo
1,Canelones,Canelones,4536,1751,520187,Canelones,Canelones
2,Maldonado,Maldonado,4793,1851,164300,Cerro_Largo,Maldonado
3,Salto,Salto,14163,5468,124878,Colonia,Salto
4,Colonia,Colonia del Sacramento,6106,2358,123203,Durazno,Colonia
5,Paysandú,Paysandú,13922,5375,113124,Flores,Paysandu
6,San José,San José de Mayo,4992,1927,108309,Florida,San_Jose
7,Rivera,Rivera,9370,3620,103493,Lavalleja,Rivera
8,Tacuarembó,Tacuarembó,15438,5961,90053,Maldonado,Tacuarembo
9,Cerro Largo,Melo,13648,5270,84698,Montevideo,Cerro_Largo
10,Soriano,Mercedes,9008,3478,82595,Paysandu,Soriano
11,Artigas,Artigas,11928,4605,73378,Rio_Negro,Artigas
12,Rocha,Rocha,10551,4074,68088,Rivera,Rocha
13,Florida,Florida,10417,4022,67048,Rocha,Florida
14,Lavalleja,Minas,10016,3867,58815,Salto,Lavalleja
15,Durazno,Durazno,11643,4495,57088,San_Jose,Durazno
16,Río Negro,Fray Bentos,9282,3584,54765,Soriano,Rio_Negro
17,Treinta y Tres,Treinta y Tres,9529,3679,48134,Tacuarembo,Treinta_y_Tres
18,Flores,Trinidad,5144,1986,25050,Treinta_y_Tres,Flores

In [15]:
dfm = dfm.rename(columns={"department":"_dept"})
dfm

,_dept,municipality,population,surface,mayor,creation
0,Artigas,Baltasar Brum,2608,"754,0 km²",Juan Marticorena (PN),2010-03-01
1,Artigas,Bella Unión,18 406,"547,0 km²",William Cresseri (PN),2010-03-01
2,Artigas,Tomás Gomensoro,2902,"804,5 km²",Federico Arbiza (PN),2010-03-01
3,Canelones,18 de Mayo,21 371,"11,0 km²",Adriana Sánchez (FA),2013-03-02
4,Canelones,Aguas Corrientes,1728,"51,5 km²",Marcelo Delgado (FA),2010-03-01
...,...,...,...,...,...,...
120,Treinta_y_Tres,General Enrique Martínez,(sin datos),(sin datos),Nidia Vera,2017-12-02
121,Treinta_y_Tres,Rincón,(sin datos),(sin datos),Eduardo Gonzales,2017-12-02
122,Treinta_y_Tres,Santa Clara de Olimar,2485,"482,4 km²",Pablo Echevarría (PN),2010-03-01
123,Treinta_y_Tres,Vergara,4064,"622,5 km²",José González (PN),2010-03-01
124,Treinta_y_Tres,Villa Sara,(sin datos),(sin datos),Analía Larrañaga,2017-12-02

In [16]:
df = (
    dfm
    .merge(dfd, how="left", on="_dept")
    .rename(
        columns={
            "population_x": "municipality_ppl",
            "surface": "municipality_area_km2",
            "creation": "municipality_creation_date",
            "capital": "province_capital",
            "department": "province",
            "area_km2": "province_area_km2",
            "population_y": "province_ppl"
        }
    )
    .assign(
        country_code="UY",
    )
    .drop(
        columns=["_dept", "mayor", "area_mi2", "_muni_dept"],
        axis=1
    )
)
df["province_code"] = (
    df["province"]
    .str.replace(r"A|a|E|e|I|i|O|o|U|u|\s+", "", regex=True)
    .str.upper()[:4]
    .str.replace("Í", "I", regex=False)
)
df

,municipality,municipality_ppl,municipality_area_km2,municipality_creation_date,province,province_capital,province_area_km2,province_ppl,country_code,province_code
0,Baltasar Brum,2608,"754,0 km²",2010-03-01,Artigas,Artigas,11928,73378,UY,RTGS
1,Bella Unión,18 406,"547,0 km²",2010-03-01,Artigas,Artigas,11928,73378,UY,RTGS
2,Tomás Gomensoro,2902,"804,5 km²",2010-03-01,Artigas,Artigas,11928,73378,UY,RTGS
3,18 de Mayo,21 371,"11,0 km²",2013-03-02,Canelones,Canelones,4536,520187,UY,CNLNS
4,Aguas Corrientes,1728,"51,5 km²",2010-03-01,Canelones,Canelones,4536,520187,UY,NaN
...,...,...,...,...,...,...,...,...,...,...
120,General Enrique Martínez,(sin datos),(sin datos),2017-12-02,Treinta y Tres,Treinta y Tres,9529,48134,UY,NaN
121,Rincón,(sin datos),(sin datos),2017-12-02,Treinta y Tres,Treinta y Tres,9529,48134,UY,NaN
122,Santa Clara de Olimar,2485,"482,4 km²",2010-03-01,Treinta y Tres,Treinta y Tres,9529,48134,UY,NaN
123,Vergara,4064,"622,5 km²",2010-03-01,Treinta y Tres,Treinta y Tres,9529,48134,UY,NaN
124,Villa Sara,(sin datos),(sin datos),2017-12-02,Treinta y Tres,Treinta y Tres,9529,48134,UY,NaN

In [51]:
import re

In [65]:
df[df["province_code"].notna()]

,municipality,municipality_ppl,municipality_area_km2,municipality_creation_date,province,province_capital,province_area_km2,province_ppl,country_code,province_code
0,Baltasar Brum,2608,"754,0 km²",2010-03-01,Artigas,Artigas,11928,73378,UY,RTGS
1,Bella Unión,18 406,"547,0 km²",2010-03-01,Artigas,Artigas,11928,73378,UY,RTGS
2,Tomás Gomensoro,2902,"804,5 km²",2010-03-01,Artigas,Artigas,11928,73378,UY,RTGS
3,18 de Mayo,21 371,"11,0 km²",2013-03-02,Canelones,Canelones,4536,520187,UY,CNLNS

In [58]:
for p in df["province"].unique():
    print(
        re.sub(r"A|a|E|e|I|i|O|o|U|u|\s+", "", p).upper()[:4].replace("Í", "I")
    )

RTGS
CNLN
CRRL
CLN
DRZN
FLRS
FLRD
LVLL
MLDN
MNTV
PYSN
RING
RVR
RCH
SLT
SNJS
SRN
TCRM
TRNT

In [47]:
dft = tuy.transform(divisions, municipalities)
dft

,municipality,municipality_ppl,municipality_area_km2,municipality_creation_date,province,province_capital,province_area_km2,province_ppl,country_code,municipality_id
0,Baltasar Brum,2608,"754,0 km²",2010-03-01,Artigas,Artigas,11928,73378,UY,UY_RTGS_00
1,Bella Unión,18 406,"547,0 km²",2010-03-01,Artigas,Artigas,11928,73378,UY,UY_RTGS_01
2,Tomás Gomensoro,2902,"804,5 km²",2010-03-01,Artigas,Artigas,11928,73378,UY,UY_RTGS_02
3,18 de Mayo,21 371,"11,0 km²",2013-03-02,Canelones,Canelones,4536,520187,UY,UY_CNLN_00
4,Aguas Corrientes,1728,"51,5 km²",2010-03-01,Canelones,Canelones,4536,520187,UY,UY_CNLN_01
...,...,...,...,...,...,...,...,...,...,...
120,General Enrique Martínez,(sin datos),(sin datos),2017-12-02,Treinta y Tres,Treinta y Tres,9529,48134,UY,UY_TRNT_01
121,Rincón,(sin datos),(sin datos),2017-12-02,Treinta y Tres,Treinta y Tres,9529,48134,UY,UY_TRNT_02
122,Santa Clara de Olimar,2485,"482,4 km²",2010-03-01,Treinta y Tres,Treinta y Tres,9529,48134,UY,UY_TRNT_03
123,Vergara,4064,"622,5 km²",2010-03-01,Treinta y Tres,Treinta y Tres,9529,48134,UY,UY_TRNT_04
124,Villa Sara,(sin datos),(sin datos),2017-12-02,Treinta y Tres,Treinta y Tres,9529,48134,UY,UY_TRNT_05

In [22]:
import numpy as np

In [49]:
dft["municipality_area_km2"] = (
    dft["municipality_area_km2"]
    .replace(r"\s+km.*", " ", regex=True)
    .replace(r"\(sin\sdatos\)", pd.NA, regex=True)
    .replace(r"\,", ".", regex=True)
    .str.split()
)
dft.loc[dft["municipality_area_km2"].notna(), "municipality_area_km2"] = (
    dft
    .loc[dft["municipality_area_km2"].notna(), "municipality_area_km2"]
    .apply(lambda m: m[0])
    .apply(float)
)
dft

,municipality,municipality_ppl,municipality_area_km2,municipality_creation_date,province,province_capital,province_area_km2,province_ppl,country_code,municipality_id
0,Baltasar Brum,2608,754.0,2010-03-01,Artigas,Artigas,11928,73378,UY,UY_RTGS_00
1,Bella Unión,18 406,547.0,2010-03-01,Artigas,Artigas,11928,73378,UY,UY_RTGS_01
2,Tomás Gomensoro,2902,804.5,2010-03-01,Artigas,Artigas,11928,73378,UY,UY_RTGS_02
3,18 de Mayo,21 371,11.0,2013-03-02,Canelones,Canelones,4536,520187,UY,UY_CNLN_00
4,Aguas Corrientes,1728,51.5,2010-03-01,Canelones,Canelones,4536,520187,UY,UY_CNLN_01
...,...,...,...,...,...,...,...,...,...,...
120,General Enrique Martínez,(sin datos),<NA>,2017-12-02,Treinta y Tres,Treinta y Tres,9529,48134,UY,UY_TRNT_01
121,Rincón,(sin datos),<NA>,2017-12-02,Treinta y Tres,Treinta y Tres,9529,48134,UY,UY_TRNT_02
122,Santa Clara de Olimar,2485,482.4,2010-03-01,Treinta y Tres,Treinta y Tres,9529,48134,UY,UY_TRNT_03
123,Vergara,4064,622.5,2010-03-01,Treinta y Tres,Treinta y Tres,9529,48134,UY,UY_TRNT_04
124,Villa Sara,(sin datos),<NA>,2017-12-02,Treinta y Tres,Treinta y Tres,9529,48134,UY,UY_TRNT_05

In [36]:
dft

,municipality,municipality_ppl,municipality_area_km2,municipality_creation_date,province,province_capital,province_area_km2,province_ppl,country_code,municipality_id
0,Baltasar Brum,2608,NaN,2010-03-01,Artigas,Artigas,11928,73378,UY,UY_RTGS_00
1,Bella Unión,18 406,NaN,2010-03-01,Artigas,Artigas,11928,73378,UY,UY_RTGS_01
2,Tomás Gomensoro,2902,NaN,2010-03-01,Artigas,Artigas,11928,73378,UY,UY_RTGS_02
3,18 de Mayo,21 371,NaN,2013-03-02,Canelones,Canelones,4536,520187,UY,UY_CNLN_00
4,Aguas Corrientes,1728,NaN,2010-03-01,Canelones,Canelones,4536,520187,UY,UY_CNLN_01
...,...,...,...,...,...,...,...,...,...,...
120,General Enrique Martínez,(sin datos),<NA>,2017-12-02,Treinta y Tres,Treinta y Tres,9529,48134,UY,UY_TRNT_01
121,Rincón,(sin datos),<NA>,2017-12-02,Treinta y Tres,Treinta y Tres,9529,48134,UY,UY_TRNT_02
122,Santa Clara de Olimar,2485,NaN,2010-03-01,Treinta y Tres,Treinta y Tres,9529,48134,UY,UY_TRNT_03
123,Vergara,4064,NaN,2010-03-01,Treinta y Tres,Treinta y Tres,9529,48134,UY,UY_TRNT_04
124,Villa Sara,(sin datos),<NA>,2017-12-02,Treinta y Tres,Treinta y Tres,9529,48134,UY,UY_TRNT_05